apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config"
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
data:
  {{ (.Files.Glob "config/*").AsConfig | nindent 2 }}
