apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type: {{ .Values.service.type }}
  ports:
    - name: mqtt
      port: {{ .Values.service.mqttPort }}
      protocol: TCP
      targetPort: mqtt
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      protocol: TCP
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-headless"
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: mqtt
    - name: epmd
      port: 4369
      protocol: TCP
      targetPort: epmd
    - name: cluster
      port: 44053
      protocol: TCP
      targetPort: cluster
