apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 300
      template:
        metadata:
          labels:
            app: {{ .Chart.Name }}
            app.kubernetes.io/name: {{ .Chart.Name }}
            app.kubernetes.io/component: cronjob
            app.kubernetes.io/part-of: {{ .Chart.Name }}
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
          volumes:
            - name: secrets
              secret:
                secretName: {{ .Values.secretName }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - "-config"
                - "/var/secrets/config.yaml"
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
              volumeMounts:
                - name: secrets
                  mountPath: /var/secrets
                  readOnly: true
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
