apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  serviceName: "{{ .Chart.Name }}-headless"
  updateStrategy:
    type: RollingUpdate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mqtt
              containerPort: 1883
            - name: dashboard
              containerPort: 18083
            - name: erlang-epmd
              containerPort: 4369
            - name: erlang-dist
              containerPort: 4370
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: EMQX_NAME
              value: {{ .Chart.Name }}
            - name: EMQX_HOST
              value: $(POD_NAME)
            - name: EMQX_NODE__NAME
              value: $(EMQX_NAME)@$(POD_NAME).{{ .Chart.Name }}-headless.{{ .Release.Namespace }}.svc.cluster.local
            - name: EMQX_NODE__COOKIE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: node-cookie
            - name: EMQX_DASHBOARD__DEFAULT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: dashboard-username
            - name: EMQX_DASHBOARD__DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: dashboard-password
            - name: EMQX_AUTHENTICATION__1__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: redis-password
          volumeMounts:
            - name: config
              mountPath: /opt/emqx/etc/emqx.conf
              subPath: emqx.conf
            - name: config
              mountPath: /opt/emqx/etc/acl.conf
              subPath: acl.conf
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /status
              port: 18083
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /status
              port: 18083
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30

        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - containerPort: 6379
              name: redis
          args:
            - "--save"
            - ""
            - "--appendonly"
            - "no"
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: redis-password
            - name: REDISCLI_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: redis-password
          volumeMounts:
            - name: secrets
              mountPath: /opt/users.txt
              subPath: users
            - name: config
              mountPath: /opt/load-users.sh
              subPath: load-users.sh
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - "redis-cli"
                - "ping"
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "/opt/load-users.sh"

      volumes:
        - name: config
          configMap:
            name: "{{ .Chart.Name }}-config"
        - name: secrets
          secret:
            secretName: {{ .Values.secretName }}
