apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.secretName }}
  labels:
    app: monitoring
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  itemPath: "vaults/k8s-secrets/items/grafana-admin"
