image:
  repository: ghcr.io/markis/nullclaw-container
  tag: "v0.1.1"
  pullPolicy: IfNotPresent

deployment:
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  host: nullclaw.markis.network

secretName: nullclaw-secrets
