image:
  repository: ghcr.io/markis/lineup
  tag: "latest"
  pullPolicy: Always

replicas: 1

deployment:
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  host: lineup.markis.network
