apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: budget-importer-secrets
  labels:
    app: budget-importer
    app.kubernetes.io/name: budget-importer
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: budget-importer
spec:
  itemPath: "vaults/k8s-secrets/items/budget-importer"
