# =============================================================================
# Apps - App-of-Apps Pattern
# =============================================================================
# Parent application that generates ArgoCD Applications for each app directory.
# Add new apps to argocd/apps/values.yaml to have them automatically deployed.
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/markis/cluster-config.git
    targetRevision: main
    path: argocd/apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
