# =============================================================================
# 1Password Connect - Secrets Automation
# =============================================================================
# 1Password Connect provides a secure way to access 1Password items from
# your infrastructure. It runs a local API server that integrates with
# Kubernetes to inject secrets from 1Password vaults.
#
# Helm Chart: https://github.com/1Password/connect-helm-charts
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password-connect
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # -----------------------------------------------------------------------------
  # Project Configuration
  # -----------------------------------------------------------------------------
  project: default

  # -----------------------------------------------------------------------------
  # Source Configuration - Helm Chart
  # -----------------------------------------------------------------------------
  source:
    # Official 1Password Connect Helm repository
    repoURL: https://1password.github.io/connect-helm-charts
    chart: connect
    # Pin to specific version for reproducibility
    targetRevision: 1.17.0
    helm:
      releaseName: 1password-connect
      values: |
        # =======================================================================
        # Connect Server Configuration
        # =======================================================================
        connect:
          # Number of Connect server replicas
          replicas: 1

          # Resource limits and requests
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi

          # Service account configuration
          serviceAccount:
            create: true
            name: onepassword-connect

          # Credentials file configuration
          # IMPORTANT: You must create a secret containing your 1password-credentials.json
          # kubectl create secret generic op-credentials --from-file=1password-credentials.json -n 1password
          credentials:
            # Use existing secret (recommended)
            existingSecret: op-credentials
            # Key in the secret containing the credentials JSON
            secretKey: 1password-credentials.json

        # =======================================================================
        # Operator Configuration
        # =======================================================================
        operator:
          # Enable the 1Password Kubernetes Operator
          # This allows using OnePasswordItem CRDs to sync secrets
          create: true

          # Number of operator replicas
          replicas: 1

          # Resource limits and requests
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi

          # Watch all namespaces for OnePasswordItem resources
          # Set to specific namespace to restrict
          watchNamespace: []

          # Token for operator to communicate with Connect server
          # IMPORTANT: Create a secret containing your operator token
          # kubectl create secret generic onepassword-token --from-literal=token=<your-token> -n 1password
          token:
            existingSecret: onepassword-token
            key: token

        # =======================================================================
        # Service Configuration
        # =======================================================================
        service:
          # Service type for Connect API
          type: ClusterIP
          # Port for the Connect API
          port: 8080

        # =======================================================================
        # Ingress Configuration
        # =======================================================================
        ingress:
          # Disable ingress by default (Connect should only be internal)
          enabled: false

  # -----------------------------------------------------------------------------
  # Destination Configuration
  # -----------------------------------------------------------------------------
  destination:
    server: https://kubernetes.default.svc
    # 1Password Connect installs in its own namespace
    namespace: 1password

  # -----------------------------------------------------------------------------
  # Sync Policy Configuration
  # -----------------------------------------------------------------------------
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # -----------------------------------------------------------------------------
  # Sync Waves
  # -----------------------------------------------------------------------------
  # Use sync waves if you need to ensure credentials secrets exist first
  # metadata:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: "1"
