# =============================================================================
# ArgoCD - GitOps Continuous Delivery
# =============================================================================
# ArgoCD manages itself! This is a common pattern where ArgoCD deploys and
# updates its own installation. This ensures ArgoCD configuration is also
# managed via GitOps.
#
# Helm Chart: https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  # Finalizer for cleanup when Application is deleted
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # -----------------------------------------------------------------------------
  # Project Configuration
  # -----------------------------------------------------------------------------
  project: default

  # -----------------------------------------------------------------------------
  # Source Configuration - Helm Chart
  # -----------------------------------------------------------------------------
  source:
    # Official ArgoCD Helm repository
    repoURL: https://argoproj.github.io/argo-helm
    # Helm chart name
    chart: argo-cd
    # Chart version - pin to specific version for reproducibility
    # Check https://github.com/argoproj/argo-helm/releases for latest
    targetRevision: 7.7.12
    # Helm values configuration
    helm:
      # Release name for the Helm installation
      releaseName: argocd
      # Inline values (alternatively use valuesFiles for external files)
      values: |
        # =======================================================================
        # Global Configuration
        # =======================================================================
        global:
          # Additional labels applied to all resources
          additionalLabels:
            app.kubernetes.io/part-of: argocd

        # =======================================================================
        # Dex Configuration
        # =======================================================================
        dex:
          # Disable TLS for dex server (simplifies setup)
          certificateSecret:
            enabled: false

        # =======================================================================
        # Server Configuration
        # =======================================================================
        server:
          # Number of replicas for HA (use 2+ for production)
          replicas: 1
          # Ingress configuration (enable if using ingress controller)
          ingress:
            enabled: false
            # Uncomment and configure for your ingress setup:
            # ingressClassName: traefik
            # hosts:
            #   - argocd.example.com
            # tls:
            #   - secretName: argocd-tls
            #     hosts:
            #       - argocd.example.com

        # =======================================================================
        # Controller Configuration
        # =======================================================================
        controller:
          # Number of replicas (only 1 active at a time due to leader election)
          replicas: 1
          # Resource limits and requests
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi

        # =======================================================================
        # Repo Server Configuration
        # =======================================================================
        repoServer:
          # Replicas for repo server (can scale for performance)
          replicas: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi

        # =======================================================================
        # Redis Configuration
        # =======================================================================
        redis:
          # Use built-in Redis (set to false to use external Redis)
          enabled: true
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi

        # =======================================================================
        # Application Set Controller
        # =======================================================================
        applicationSet:
          # Enable ApplicationSet controller for generating Applications
          enabled: true
          replicas: 1

        # =======================================================================
        # Notifications Controller
        # =======================================================================
        notifications:
          # Enable notifications (Slack, email, webhook, etc.)
          enabled: true

  # -----------------------------------------------------------------------------
  # Destination Configuration
  # -----------------------------------------------------------------------------
  destination:
    server: https://kubernetes.default.svc
    # ArgoCD installs into its own namespace
    namespace: argocd

  # -----------------------------------------------------------------------------
  # Sync Policy Configuration
  # -----------------------------------------------------------------------------
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # ServerSideApply helps with large CRDs like ArgoCD's
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # -----------------------------------------------------------------------------
  # Ignore Differences
  # -----------------------------------------------------------------------------
  # Some fields are managed by controllers and should be ignored during diff
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
