# =============================================================================
# Budget Importer - Scheduled Data Import Job
# =============================================================================
# CronJob that imports budget data every 6 hours. Uses 1Password Connect
# to securely inject configuration secrets.
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budget-importer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/markis/cluster-config.git
    targetRevision: main
    path: apps/budget-importer

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
