# =============================================================================
# MQTT - EMQX Message Broker Cluster
# =============================================================================
# EMQX MQTT broker running as a 3-node cluster with Redis authentication.
# Secrets are managed via 1Password Connect.
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mqtt
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/markis/cluster-config.git
    targetRevision: main
    path: apps/mqtt

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
