apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config"
  labels:
    app: {{ .Chart.Name }}
data:
  configuration.yaml: |
    # Home Assistant integration
    homeassistant: {{ .Values.homeassistant.enabled }}

    # MQTT settings
    mqtt:
      server: {{ .Values.mqtt.server }}
      base_topic: {{ .Values.mqtt.baseTopic }}
      user: ${MQTT_USERNAME}
      password: ${MQTT_PASSWORD}

    # Serial settings
    serial:
      port: {{ .Values.serial.port }}
      baudrate: {{ .Values.serial.baudrate }}
      adapter: {{ .Values.serial.adapter }}
      disable_led: {{ .Values.serial.disableLed }}

    # Advanced settings
    advanced:
      log_level: {{ .Values.log.level }}
      pan_id: ${ZIGBEE_PAN_ID}
      ext_pan_id: ${ZIGBEE_EXT_PAN_ID}
      channel: {{ .Values.advanced.channel }}
      network_key: ${ZIGBEE_NETWORK_KEY}
      transmit_power: {{ .Values.advanced.transmitPower }}
      homeassistant_discovery_topic: {{ .Values.homeassistant.discoveryTopic }}
      homeassistant_status_topic: {{ .Values.homeassistant.statusTopic }}

    # Frontend settings
    frontend:
      port: {{ .Values.frontend.port }}

    # Device options
    device_options:
      # Devices will retain their friendly names between restarts
      retain: true
