apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-scripts
  labels:
    app: {{ .Chart.Name }}
data:
  backup.sh: |
{{ .Files.Get "scripts/backup.sh" | indent 4 }}
  restore.sh: |
{{ .Files.Get "scripts/restore.sh" | indent 4 }}
  init-config.sh: |
{{ .Files.Get "scripts/init-config.sh" | indent 4 }}
