apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-template
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: {{ .Chart.Name }}
data:
  config.toml: |
{{ .Files.Get "files/config.toml" | indent 4 }}
