apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: mqtt-secrets
  labels:
    app: mqtt
    app.kubernetes.io/name: mqtt
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: mqtt
spec:
  itemPath: "vaults/k8s-secrets/items/mqtt"
