apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mqtt
  labels:
    app: mqtt
spec:
  serviceName: mqtt-headless
  updateStrategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      serviceAccountName: mqtt
      containers:
        - name: mqtt
          image: emqx/emqx:5.8.8
          ports:
            - name: mqtt
              containerPort: 1883
            - name: dashboard
              containerPort: 18083
            - name: erlang-epmd
              containerPort: 4369
            - name: erlang-dist
              containerPort: 4370
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: EMQX_NAME
              value: mqtt
            - name: EMQX_HOST
              value: $(POD_NAME)
            - name: EMQX_NODE__NAME
              value: $(EMQX_NAME)@$(POD_NAME).mqtt-headless.default.svc.cluster.local
            - name: EMQX_NODE__COOKIE
              valueFrom:
                secretKeyRef:
                  name: mqtt-secrets
                  key: node-cookie
            - name: EMQX_DASHBOARD__DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mqtt-secrets
                  key: dashboard-password
          volumeMounts:
            - name: mqtt-config
              mountPath: /opt/emqx/etc/emqx.conf
              subPath: emqx.conf
            - name: mqtt-config
              mountPath: /opt/emqx/etc/acl.conf
              subPath: acl.conf
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /status
              port: 18083
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /status
              port: 18083
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30

        - name: mqtt-redis
          image: redis:7.0.15
          ports:
            - containerPort: 6379
              name: redis
          args:
            - "--save"
            - ""
            - "--appendonly"
            - "no"
          env:
            - name: MASTER
              value: "true"
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          volumeMounts:
            - name: mqtt-secrets
              mountPath: /opt/users.txt
              subPath: users
            - name: mqtt-config
              mountPath: /opt/load-users.sh
              subPath: load-users.sh
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - "redis-cli"
                - "ping"
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "/opt/load-users.sh"

      volumes:
        - name: mqtt-config
          configMap:
            name: mqtt-config
        - name: mqtt-secrets
          secret:
            secretName: mqtt-secrets
